config-version = 2

# Start AeroSpace at login
start-at-login = true

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

[workspace-to-monitor-force-assignment]
1 = "main"
2 = "main"
3 = "main"
4 = "main"
5 = "main"
6 = "main"
7 = "main"
8 = "main"
9 = "main"
10 = "main"

[mode.main.binding]
#
# Bindings are configured based on the [Cosmic Desktop
# Environment](https://system76.com/cosmic) defaults (with minimal
# customizations)
#
# On systems with Cosmic installed, the defaults can be found at:
# /usr/share/cosmic/com.system76.CosmicSettings.Shortcuts/v1/defaults
#

# alt-shift-esc = "TODO: System(LogOut)"
# alt-esc = "TODO: System(LockScreen)"
# alt-q = "close --quit-if-last-window"

alt-h = "focus --boundaries-action wrap-around-the-workspace left"
alt-j = "focus --boundaries-action wrap-around-the-workspace down"
alt-k = "focus --boundaries-action wrap-around-the-workspace up"
alt-l = "focus --boundaries-action wrap-around-the-workspace right"
# alt-u = "TODO: Focus(Out)"
# alt-i = "TODO: Focus(In)"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-0 = "workspace 10"
alt-shift-1 = "move-node-to-workspace --focus-follows-window 1"
alt-shift-2 = "move-node-to-workspace --focus-follows-window 2"
alt-shift-3 = "move-node-to-workspace --focus-follows-window 3"
alt-shift-4 = "move-node-to-workspace --focus-follows-window 4"
alt-shift-5 = "move-node-to-workspace --focus-follows-window 5"
alt-shift-6 = "move-node-to-workspace --focus-follows-window 6"
alt-shift-7 = "move-node-to-workspace --focus-follows-window 7"
alt-shift-8 = "move-node-to-workspace --focus-follows-window 8"
alt-shift-9 = "move-node-to-workspace --focus-follows-window 9"
alt-shift-0 = "move-node-to-workspace --focus-follows-window 10"

alt-ctrl-h = "workspace --wrap-around prev"
alt-ctrl-j = "workspace --wrap-around next"
alt-ctrl-k = "workspace --wrap-around prev"
alt-ctrl-l = "workspace --wrap-around next"
alt-shift-ctrl-h = "move-node-to-workspace prev"
alt-shift-ctrl-j = "move-node-to-workspace next"
alt-shift-ctrl-k = "move-node-to-workspace prev"
alt-shift-ctrl-l = "move-node-to-workspace next"

alt-o = "layout horizontal vertical"
alt-s = "layout tiles accordion"
# alt-y = "TODO: ToggleTiling"
alt-g = "layout tiling floating"
alt-x = "swap right"

alt-m = "fullscreen"
alt-f = "macos-native-fullscreen"
alt-r = "resize height +50"
alt-shift-r = "resize height -50"
alt-ctrl-r = "mode resize"

alt-b = "exec-and-forget open -na /Applications/Firefox.app"
alt-t = "exec-and-forget open -na /Applications/Ghostty.app"

alt-ctrl-shift-r = "reload-config"

[mode.resize.binding]
equal = "balance-sizes"

h = "resize width -25"
j = "resize height +25"
k = "resize height -25"
l = "resize width +25"

shift-h = "resize width -50"
shift-j = "resize height +50"
shift-k = "resize height -50"
shift-l = "resize width +50"

enter = "mode main"
esc = "mode main"
