#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# # bar settings
# yabai -m config top_padding 0

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus

yabai -m config window_placement second_child
yabai -m config window_topmost on

yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow on

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# Mouse support
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 20

floating_apps=(
  'Installer'
  '^System Information$'
  '^System Preferences$'
)

for app in "${floating_apps[@]}"; do
  yabai -m rule --add app="$app" manage=off
done

# float system preferences
yabai -m rule --add title='Preferences$' manage=off
# float settings windows
yabai -m rule --add title='Settings$' manage=off

# disable opacity change on focus
yabai -m rule --add app="Plex" opacity=1.0

echo "yabai configuration loaded.."
